version: '3.8'

services:
  marktde-scraper:
    build: .
    container_name: marktde-scraper-frontend
    ports:
      - "3000:3000"
      - "3001:3001"  # WebSocket port
    volumes:
      # Mount data directory to persist CSV files
      - ./data:/app/data
      # Mount scraper directory to access existing scripts
      - ../scraper:/app/scraper
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  scraper_data:
    driver: local