version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: instagram-tracker-db
    environment:
      POSTGRES_DB: instagram_tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/migrations:/migrations
    restart: unless-stopped

volumes:
  postgres_data: 